In [12]:
#QUESTION 1

import numpy as n
arr = n.random.randint(1,60,60)
arr2=arr.reshape(12,5)
print(arr2)
def last_row(row):
     print('Minimum --->',row.min())
     print('Maximum -->',row.max())
     print('Average --->',row.mean())
     count =0
     for i in row:
        if (i%2==0):
            count+=1
     print('No. of even numbers:',count)

row=arr2[11]  
       
print('In last row:',row)   
last_row(row)
            

     

[[34 16 27 44 33]
 [19 20 58 16 20]
 [17 25  9 39 19]
 [23 11  4 11 28]
 [24 32 11 35 31]
 [15 11 33 48 29]
 [46 52  2 53 42]
 [57 16 22 28 45]
 [19  7 23 43 40]
 [43 40  7 13 37]
 [58  5  3  6 44]
 [15  4  6  4 51]]
In last row: [15  4  6  4 51]
Minimum ---> 4
Maximum --> 51
Average ---> 16.0
No. of even numbers: 3


In [17]:
#QUESTION 2

import numpy as n
arr=n.array([[1,2,3],[5,7,2],[5,9,8]])
print(arr)
print('After slicing:')
print(arr[0:,-1:-4:-1])


[[1 2 3]
 [5 7 2]
 [5 9 8]]
After slicing:
[[3 2 1]
 [2 7 5]
 [8 9 5]]
