In [1]:
#QUESTION 1
import numpy as n
arr =n.random.random((12,5))
print(arr)
print('The last row of the array is:',arr[11:12])
arr[11]=[1.78,2.56,3.333,4.43,5.8796]
print('After updating the last row array becomes:')
print(arr)



[[0.19136785 0.13317992 0.63341148 0.76756574 0.69197747]
 [0.80646419 0.9242672  0.74256346 0.47310741 0.66436091]
 [0.24902349 0.70843258 0.83762365 0.25809092 0.66927988]
 [0.04342415 0.97170975 0.8261931  0.68245629 0.52924003]
 [0.40475843 0.05250621 0.28217344 0.14347956 0.41472991]
 [0.48377228 0.59621882 0.0310784  0.92962508 0.83177761]
 [0.52367019 0.0257822  0.76029392 0.05611136 0.37817876]
 [0.44698902 0.32797644 0.68912959 0.7415884  0.68499537]
 [0.060827   0.56290239 0.096074   0.98076717 0.66765307]
 [0.76225555 0.6326804  0.70623003 0.97461115 0.89293007]
 [0.1394973  0.848308   0.65023731 0.67898965 0.74074022]
 [0.62185463 0.68544326 0.20088695 0.23983904 0.89069245]]
The last row of the array is: [[0.62185463 0.68544326 0.20088695 0.23983904 0.89069245]]
After updating the last row array becomes:
[[0.19136785 0.13317992 0.63341148 0.76756574 0.69197747]
 [0.80646419 0.9242672  0.74256346 0.47310741 0.66436091]
 [0.24902349 0.70843258 0.83762365 0.25809092 0.6692798

In [29]:
#QUESTION 2
arr2 = n.random.randint(1,60,60)
print(arr2)
arr3=arr2.reshape(12,5)
print(arr3)
i =0
for row in arr3:
    print('The maximun value in row ',i,':',max(row))
    print('The minimum value in row ',i,':',min(row))
    i+=1

[25 38 21  6 28 12 51 53  5 47  6 20 33 10 32 30 37 22 15 40 11 25 25 20
 55 43 48 11 58 50 40 37 29 40  3 45 50 43 45 30 49 18 29 46  5 17 22 53
 38 19 35 40 19 42  4 16 51 56 40 44]
[[25 38 21  6 28]
 [12 51 53  5 47]
 [ 6 20 33 10 32]
 [30 37 22 15 40]
 [11 25 25 20 55]
 [43 48 11 58 50]
 [40 37 29 40  3]
 [45 50 43 45 30]
 [49 18 29 46  5]
 [17 22 53 38 19]
 [35 40 19 42  4]
 [16 51 56 40 44]]
The maximun value in row  0 : 38
The minimum value in row  0 : 6
The maximun value in row  1 : 53
The minimum value in row  1 : 5
The maximun value in row  2 : 33
The minimum value in row  2 : 6
The maximun value in row  3 : 40
The minimum value in row  3 : 15
The maximun value in row  4 : 55
The minimum value in row  4 : 11
The maximun value in row  5 : 58
The minimum value in row  5 : 11
The maximun value in row  6 : 40
The minimum value in row  6 : 3
The maximun value in row  7 : 50
The minimum value in row  7 : 30
The maximun value in row  8 : 49
The minimum value in row  8 : 5
The maximu